name: Helium Auto Update

on:
  schedule:
    - cron: "0 8 * * *" # runs every day at 08:00 UTC
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  # 1. Update the Manifest File
  update-manifest:
    runs-on: ubuntu-latest
    outputs:
      changes_detected: ${{ steps.check.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run update script
        run: bash .github/workflows/grab_latest.sh
        
      - name: Check and Commit
        id: check
        run: |
          git config --global user.name "helium-bot"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          if [[ -n $(git status -s net.imput.helium.yml) ]]; then
            echo "changes_detected=true" >> "$GITHUB_OUTPUT"
            VERSION=$(grep -m1 'version:' version.txt | awk '{print $2}')
            git add net.imput.helium.yml net.imput.helium.metainfo.xml version.txt
            git commit -m "update: helium $VERSION"
            git push origin HEAD:main
          else
            echo "changes_detected=false" >> "$GITHUB_OUTPUT"
          fi

  # 2. Build the Flatpaks
  build-flatpak:
    needs: update-manifest
    if: needs.update-manifest.outputs.changes_detected == 'true'
    strategy:
      matrix:
        include:
          - flatpak_arch: x86_64
            file_arch: x86_64
            runner: ubuntu-latest
          - flatpak_arch: aarch64
            file_arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Mark safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Install Flatpak Builder
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Setup Flathub
        run: flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

      - name: Build and Bundle
        run: |
          VERSION=$(grep -m1 'version:' version.txt | awk '{print $2}')
          flatpak-builder --arch=${{ matrix.flatpak_arch }} --user --repo=repo --force-clean --install-deps-from=flathub build-dir net.imput.helium.yml
          flatpak build-bundle --arch=${{ matrix.flatpak_arch }} repo "helium-${VERSION}-${{ matrix.file_arch }}.flatpak" net.imput.helium

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flatpak-${{ matrix.file_arch }}
          path: "*.flatpak"
